# version: '3.9'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - shared

  monitor:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    networks:
      - shared

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    networks:
      - shared

  redis:
    image: redis:7
    networks:
      - shared

volumes:
  db_data:
    external: true
    name: redes_usach

networks:
  shared:
    external: true
    name: redes_usach
